//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpreadInfo {
    
    
    [System.SerializableAttribute()]
    public class ActorDBData : DefaultDataType {
        
        [UnityEngine.SerializeField()]
        private int m_Code;
        
        [UnityEngine.SerializeField()]
        private string m_Name;
        
        public int Code {
            get {
                return this.m_Code;
            }
        }
        
        public string Name {
            get {
                return this.m_Name;
            }
        }
    }
    
    public class ActorDBDataTable : DefaultDataTable<SpreadInfo.ActorDBData> {
    }
}
