//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpreadInfo {
    
    
    [System.SerializableAttribute()]
    public class ItemDBData : DefaultDataType {
        
        [UnityEngine.SerializeField()]
        private int m_Code;
        
        [UnityEngine.SerializeField()]
        private string m_Name;
        
        [UnityEngine.SerializeField()]
        private string m_Description;
        
        [UnityEngine.SerializeField()]
        private int m_HealHP;
        
        [UnityEngine.SerializeField()]
        private int m_HealsHP;
        
        [UnityEngine.SerializeField()]
        private bool m_Revive;
        
        [UnityEngine.SerializeField()]
        private bool m_ReviveAll;
        
        [UnityEngine.SerializeField()]
        private int m_HealMP;
        
        [UnityEngine.SerializeField()]
        private int m_HealsMP;
        
        [UnityEngine.SerializeField()]
        private float m_DEFPower;
        
        [UnityEngine.SerializeField()]
        private SpreadInfo.DefenceType m_DEFType;
        
        [UnityEngine.SerializeField()]
        private bool m_DEFReflect;
        
        [UnityEngine.SerializeField()]
        private float m_ATR;
        
        [UnityEngine.SerializeField()]
        private int m_ATRCon;
        
        [UnityEngine.SerializeField()]
        private SpreadInfo.EffectType m_Effect;
        
        [UnityEngine.SerializeField()]
        private float m_EffectPower;
        
        [UnityEngine.SerializeField()]
        private int m_EffectCon;
        
        [UnityEngine.SerializeField()]
        private SpreadInfo.EffectTargetType m_EffectTarget;
        
        public int Code {
            get {
                return this.m_Code;
            }
        }
        
        public string Name {
            get {
                return this.m_Name;
            }
        }
        
        public string Description {
            get {
                return this.m_Description;
            }
        }
        
        public int HealHP {
            get {
                return this.m_HealHP;
            }
        }
        
        public int HealsHP {
            get {
                return this.m_HealsHP;
            }
        }
        
        public bool Revive {
            get {
                return this.m_Revive;
            }
        }
        
        public bool ReviveAll {
            get {
                return this.m_ReviveAll;
            }
        }
        
        public int HealMP {
            get {
                return this.m_HealMP;
            }
        }
        
        public int HealsMP {
            get {
                return this.m_HealsMP;
            }
        }
        
        public float DEFPower {
            get {
                return this.m_DEFPower;
            }
        }
        
        public SpreadInfo.DefenceType DEFType {
            get {
                return this.m_DEFType;
            }
        }
        
        public bool DEFReflect {
            get {
                return this.m_DEFReflect;
            }
        }
        
        public float ATR {
            get {
                return this.m_ATR;
            }
        }
        
        public int ATRCon {
            get {
                return this.m_ATRCon;
            }
        }
        
        public SpreadInfo.EffectType Effect {
            get {
                return this.m_Effect;
            }
        }
        
        public float EffectPower {
            get {
                return this.m_EffectPower;
            }
        }
        
        public int EffectCon {
            get {
                return this.m_EffectCon;
            }
        }
        
        public SpreadInfo.EffectTargetType EffectTarget {
            get {
                return this.m_EffectTarget;
            }
        }
    }
    
    public class ItemDBDataTable : DefaultDataTable<SpreadInfo.ItemDBData> {
    }
}
