//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpreadInfo {
    
    
    [System.SerializableAttribute()]
    public class ScriptDBData : DefaultDataType {
        
        [UnityEngine.SerializeField()]
        private int m_Actor;
        
        [UnityEngine.SerializeField()]
        private string m_Script;
        
        public int Actor {
            get {
                return this.m_Actor;
            }
        }
        
        public string Script {
            get {
                return this.m_Script;
            }
        }
    }
    
    public class ScriptDBDataTable : ListTypeDataTable<SpreadInfo.ScriptDBData> {
    }
}
