//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpreadInfo {
    
    
    [System.SerializableAttribute()]
    public class EverytimeEventDBData : DefaultDataType {
        
        [UnityEngine.SerializeField()]
        private int m_Code;
        
        [UnityEngine.SerializeField()]
        private string m_Condition;
        
        [UnityEngine.SerializeField()]
        private int m_Target;
        
        public int Code {
            get {
                return this.m_Code;
            }
        }
        
        public string Condition {
            get {
                return this.m_Condition;
            }
        }
        
        public int Target {
            get {
                return this.m_Target;
            }
        }
    }
    
    public class EverytimeEventDBDataTable : DefaultDataTable<SpreadInfo.EverytimeEventDBData> {
    }
}
