//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpreadInfo {
    
    
    [System.SerializableAttribute()]
    public class ScriptDBData : DefaultDataType {
        
        [UnityEngine.SerializeField()]
        private SpreadInfo.WindowType m_WindowType;
        
        [UnityEngine.SerializeField()]
        private string m_Profile;
        
        [UnityEngine.SerializeField()]
        private int m_Actor;
        
        [UnityEngine.SerializeField()]
        private string m_Script;
        
        [UnityEngine.SerializeField()]
        private bool m_JustEvent;
        
        [UnityEngine.SerializeField()]
        private bool m_ClearContext;
        
        [UnityEngine.SerializeField()]
        private string m_Event;
        
        [UnityEngine.SerializeField()]
        private SpreadInfo.Timing m_EventTiming;
        
        public SpreadInfo.WindowType WindowType {
            get {
                return this.m_WindowType;
            }
        }
        
        public string Profile {
            get {
                return this.m_Profile;
            }
        }
        
        public int Actor {
            get {
                return this.m_Actor;
            }
        }
        
        public string Script {
            get {
                return this.m_Script;
            }
        }
        
        public bool JustEvent {
            get {
                return this.m_JustEvent;
            }
        }
        
        public bool ClearContext {
            get {
                return this.m_ClearContext;
            }
        }
        
        public string Event {
            get {
                return this.m_Event;
            }
        }
        
        public SpreadInfo.Timing EventTiming {
            get {
                return this.m_EventTiming;
            }
        }
    }
    
    public class ScriptDBDataTable : ListTypeDataTable<SpreadInfo.ScriptDBData> {
    }
}
